### PR TITLE
chore: remove travis badge from readme

### PR DESCRIPTION
**Pull request by SimenB**
GH actions covers all OSes, so I think this is fine. I don't have the accesses to disable appveyor webhooks, though

### CODE REVIEW

**Comment by zbjornson** [comment]
> I don't have the accesses to disable appveyor webhooks, though

Me neither.

**Comment by zbjornson** [comment]
@siimon if you're cool with this, could you merge and disable the Appveyor hooks please?

**Comment by zbjornson** [comment]
@SimenB can we close this in favor of your newer PRs?

**Comment by SimenB** [comment]
ergh, forgot about this one 😀 I'll land it for the readme change

**Pull request merged**
