### PR TITLE
Lazily initialize cluster event listeners

### LINKED ISSUE #155: Cluster event listeners are attached even if not using clusters
Because of https://github.com/siimon/prom-client/blob/426941fbc22433fff932d8f9fb09ebba4818f514/index.js#L24, https://github.com/siimon/prom-client/blob/426941fbc22433fff932d8f9fb09ebba4818f514/lib/cluster.js#L131-L170 is always ran

This results in a memory leak if `require('prom-client');` is done multiples times and the `require.cache` is blown away, as might happen in tests.

I get the following after rerunning my tests, which blow away the require cache in order to mock a dep. `(node:80194) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit`

### PR DESCRIPTION
**Pull request by zbjornson**
Sorry for the delay, forgot about this. Small change aside from indenting (try [ignoring whitespace](https://github.com/siimon/prom-client/pull/159/files?w=1)).

Fixes #155

### CODE REVIEW

**Comment by SimenB** [comment]
Thanks! (I just added a test myself)

**Comment by SimenB** [comment]
Released as 10.2.0

**Comment by zbjornson** [comment]
Thanks, sorry for being slow.

**Comment by SimenB** [comment]
No worries!

**Pull request merged**
