### PR TITLE
Init metrics to zero

### PR DESCRIPTION
**Pull request by siimon**
Fixing #118 

Added fixes for Counters, Gauges and Histograms.. Summary I'm not sure what to do about tbh.. After a quick look it's not an easy fix.

### CODE REVIEW

**Comment by siimon** [comment]
Great! Thanks! :)

**Comment by SimenB** [comment]
Ok, should be done now.

Had to revert most of the test changes when considering labels

**Comment by siimon** [comment]
LGTM!

**Comment by SimenB** [comment]
@dm3 @paulborza does this look correct? You can check the snapshot test for output with and without labels.

**Comment by paulborza** [comment]
@SimenB why initialize the metrics only when there are no labels? The metrics should be initialized to 0 across all labels.

**Comment by siimon** [comment]
How would you do that since you don't know the values for the labels? You only know the label names when you create the metric

**Comment by paulborza** [comment]
@siimon You're right; my bad. The output looks good for metrics with no labels.
Argh, I just wish there was a way Prometheus would support some sort of wildcard syntax to initialize metrics across all dimensions/labels; but apparently it doesn't.

Thanks for fixing this! :)

**Comment by paulborza** [comment]
Once merged, can you also publish the new version to the registry? Thanks

**Comment by SimenB** [comment]
>Once merged, can you also publish the new version to the registry? Thanks

Of course 🙂

**Pull request merged**
