### PR TITLE
fix: avoid mutation bug in registry.getMetricsAsJSON()

### LINKED ISSUE #287: Memory leak with default labels
Here is code example

```
const promClient = require('prom-client');

// register default label
promClient.register.setDefaultLabels({
    default_label: 'default_label_value',
});

// create counter
const counter = new promClient.Counter({
    name: 'test_counter',
    help: 'test_counter errors',
    labelNames: [ 'l1', 'l2', 'l3' ],
});

// create Internal counter with labels
const intCounter = counter.labels('l1_value', 'l2_value', 'l3_value');

intCounter.inc();

// collect metrics. And this point counter labels will be extended with default labels
console.log(JSON.stringify(promClient.register.getMetricsAsJSON(), null, 2));

// Error!
intCounter.inc();

Error: Added label "default_label" is not included in initial labelset: [ 'l1', 'l2', 'l3' ]
    at Object.keys.forEach.label (node_modules/prom-client/lib/validation.js:26:10)
    at Array.forEach (<anonymous>)
    at validateLabel (node_modules/prom-client/lib/validation.js:24:22)
    at Object.inc (node_modules/prom-client/lib/counter.js:156:3)
    at Object.<anonymous> (test.js:19:12)
```

This happens because `registry.getMetricsAs*()` mutates each metric labels with defaults.

```
getMetricsAsJSON() {
    const metrics = [];
    const defaultLabelNames = Object.keys(this._defaultLabels);

    for (const metric of this.getMetricsAsArray()) {
        const item = metric.get();

        if (item.values) {
            for (const val of item.values) {
                for (const labelName of defaultLabelNames) {
                    //
                    // leak is here
                    //
                    val.labels[labelName] = val.labels[labelName] || this._defaultLabels[labelName];
                }
            }
        }

        metrics.push(item);
    }

    return metrics;
}
```

### PR DESCRIPTION
**Pull request by doochik**
Bug introduced at #220 and fixed for .getMetricAsPrometheusString() at #273.
Fixes #287

### CODE REVIEW

**Comment by doochik** [comment]
Second commit is the simple optimisation to avoid empty loop for `getMetricAsPrometheusString()` and unnecessary loop for `getMetricsAsJSON()`

**Comment by doochik** [comment]
> Looks good to me. Can you update the change log please?

done

**Comment by doochik** [comment]
@zbjornson any change to see it merged?

**Comment by zbjornson** [comment]
@siimon @SimenB ?

**Comment by zbjornson** [comment]
@doochik sorry for the delay. Could you please rebase to fix the conflict, or do you mind if I do it for you?

**Comment by doochik** [comment]
> @doochik sorry for the delay. Could you please rebase to fix the conflict, or do you mind if I do it for you?

done

**Comment by zbjornson** [comment]
Thank you! :)

**Pull request merged**
