### PR TITLE
Add openmetrics and exemplars support

### PR DESCRIPTION
**Pull request by karlodwyer**
PR #482 hasn't been updated in a few months, so I thought @voltbit wouldn't mind if I finished this work up for him.

- Add support for OpenMetrics format
- Enforce stronger typing on registries
- Address comments and fix tests on PR: #482

### CODE REVIEW

**Comment by SimenB** [comment]
Thanks! I'll take a proper look later, but could you target the `next` branch?

**Comment by karlodwyer** [comment]
sure, I see a bunch of test failures that weren't happening locally, so let me rebase and investigate

**Review by SimenB — APPROVED** [review]
let's do it

**Comment by karlodwyer** [comment]
Excellent, do you have a timeframe for the next release in mind @SimenB ?

**Comment by SimenB** [comment]
Need to apply https://github.com/siimon/prom-client/pull/542 on `next`, then we should be good to go

**Comment by SimenB** [comment]
https://github.com/siimon/prom-client/releases/tag/v15.0.0

Finally - sorry about the delay!

**Pull request merged**
