### PR TITLE
Make tests pass in node 8

### PR DESCRIPTION
**Pull request by SimenB**
This makes the tests slower (as it just sets up an actual express server instead of mocking out the requests), but at least they pass.

### CODE REVIEW

**Comment by siimon** [comment]
A thought, if jest PR is merged, is it possible to use mock out the http module there and use it instead?

**Comment by SimenB** [comment]
I haven't tried mocking out http before. It'll be different kinds of tests, testing out calling the http module instead of the actual network request. But that's ok, I guess?

**Comment by siimon** [comment]
Yeah, but with tests used in nock doesn't make any requests either. I think asserting on the http module is fine. But I'm not sure you can catch http headers.

**Comment by SimenB** [comment]
It's part of the options sent in to `http(s).request(options, cb)`, so just asserting on `options` should be fine. We lose coverage on the cb though, unless we want to mess with eventemitters etc

**Comment by siimon** [comment]
I guess that's ok for now until we find a better solution

**Comment by SimenB** [comment]
@siimon updated with mocking out http

**Pull request merged**
