### PR TITLE
Move collection of default metrics inside an explicit function call

### PR DESCRIPTION
**Pull request by SimenB**
/cc @SkeLLLa

### CODE REVIEW

**Comment by SkeLLLa** [comment]
BTW, after merging this it will be easier to implement this: https://github.com/siimon/prom-client/issues/83

It can be done through refactoring default metrics files to have 2 or 3 methods: `start`, `stop` and `clear` (optionally). And `start` method could take metric parameters that are needed to be overridden or added. Something like I've done here (it's a bit rewritten SimenB's gc-stats plugin) : https://gitlab.com/prometheus-nodejs/prometheus-plugin-gc-stats/blob/master/lib/index.js#L80. If every default plugin can take params on start, then "global" start function for all default metrics could also take them and send them to all default metrics `start` method.

**Comment by SimenB** [comment]
Should we drop blacklisting of metrics at the same time? And do we need to be able to stop collection?

**Comment by siimon** [comment]
I'd say yes on both, at least on blacklisting. Stopping could be desired in some cases

**Comment by SimenB** [comment]
When would you want to stop?

**Comment by siimon** [comment]
One I can think of now is if you want to stop the service in a graceful way, then it would make sense to stop

**Comment by SimenB** [comment]
Fair enough 😄

Should I update this PR with removal of blacklist, or separate?

**Comment by siimon** [comment]
Update this PR :)

**Comment by SimenB** [comment]
@siimon Updated

**Comment by siimon** [comment]
LGTM! I'll merge this but I don't want to publish to npm until #100 is completed aswell.. Sounds good?

**Comment by SimenB** [comment]
Yup, sounds good!

**Pull request merged**
