### PR TITLE
Include invalid values in the error messages

### PR DESCRIPTION
**Pull request by tothandras**
`Error` only expects one argument, the `message`, which means that the invalid values were lost in the second argument.

### CODE REVIEW

**Comment by tothandras** [comment]
@SimenB Thanks for the review, I'll update the PR.

**Comment by tothandras** [comment]
@SimenB is it a feature that `util.isNumber` returns `true` for `3ms` for example, but when adding it to a summary it's not the parsed value that is used, but the string?

**Comment by SimenB** [comment]
That's a bug. `parseFloat('3ms')` returns `3`, which should be used

**Comment by siimon** [comment]
I'd say that is a bug as well and I think the best thing would be to throw an error.

The PR looks good, so fix the issues @SimenB pointed out and it's ready to be merged!

**Comment by tothandras** [comment]
@SimenB updated

**Comment by SimenB** [comment]
Too bad `toThrowErrorMatchingSnapshot` doesn't includes the type of error, just message. No problem, though :)

**Comment by SimenB** [comment]
@siimon thoughts?

**Comment by siimon** [comment]
LGTM! 👍

**Comment by SimenB** [comment]
@tothandras could you update the changelog as well? Then we'll get it released :smile:

**Comment by tothandras** [comment]
@SimenB like this?

**Comment by SimenB** [comment]
Perfect! I'll merge and release within the hour.

**Comment by SimenB** [comment]
A bit slow, but released as 10.0.4 now. Thanks!

**Pull request merged**
