### PR TITLE
Promisify pushgateway methods

### LINKED ISSUE #416: pushgateway with promised metrics()
According to the new 13.0.0 version `registry.metrics()` return a promise.
But the code was not updated everywhere.
On pushgateway side, https://github.com/siimon/prom-client/blob/master/lib/pushgateway.js#L78

When i push metrics to pushgateway, i got this kind of error
```
    TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Promise
        at write_ (_http_outgoing.js:696:11)
        at ClientRequest.write (_http_outgoing.js:661:15)
        at Pushgateway.useGateway (/home/pierrickp/works/fluctuo/data-flow/node_modules/prom-client/lib/pushgateway.js:78:7)
        at Pushgateway.pushAdd (/home/pierrickp/works/fluctuo/data-flow/node_modules/prom-client/lib/pushgateway.js:23:14)
        at /home/pierrickp/works/fluctuo/data-flow/jobs/metrics.js:36:15
        at new Promise (<anonymous>)
        at pushMetrics (/home/pierrickp/works/fluctuo/data-flow/jobs/metrics.js:28:10)
        at /home/pierrickp/works/fluctuo/data-flow/jobs/updateZones.js:162:14
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

## Instant ugly fix

`req.write(await this.registry.metrics());`
Don't forget the `async` keyword on the function.

## A better update

Convert Pushgateway methods (pushAdd / push / pushAdd / delete) to promise form with correct error/rejection handleing

### PR DESCRIPTION
**Pull request by PierrickP**
Fix #416 

:warning: breaking change on pushgateway methods.

### CODE REVIEW

**Comment by zbjornson** [comment]
Thanks for opening this. We have #392 open as well that fixes the same issue without being a breaking change. It needs tests though (as would this PR), but at this point it might be best to merge that (with the proposed fix in https://github.com/siimon/prom-client/pull/392/files#r487438436) without tests since they're difficult ones to write.

**Comment by PierrickP** [comment]
Oups i did saw the existing PR/issues ...  Sorry about that. 
They didn't continue their PR and i still think that promisify pushgateway is the right thing to do (breaking change but consistent with version 13)

I updated tests on pushgateway (using Nock for easier http mocking). Tests on pushgateway are now correctly matching the body.

I ll start using my forked branch on my projet awaiting a new version including this PR.

Thanks for your review

**Comment by zbjornson** [comment]
#419 fixed the error so that we can release 13.0.1. If you want to rebase this on master, we can stage it for v14! Apologies for the churn and thanks for your contribution.

**Comment by PierrickP** [comment]
Rebased !

Perfect if it's released on v14. Thanks for your time

**Review by zbjornson — APPROVED** [review]
Looks good, thanks! Needs a changelog entry before it can land, but I can do that if you don't have time.

**Comment by PierrickP** [comment]
@zbjornson not a question of time (more english / same as other release). I prefer you write the changelog ;)

**Comment by zbjornson** [comment]
Really sorry for the delay here. I just merged a handful of PRs that will be the next 13.x release. Once that's out, let's land this for v14.

**Review by zbjornson — APPROVED** [review]
Thanks and sorry for the delay. I just rebased on `master` and updated the changelog. Releasing v14 momentarily.

**Pull request merged**
