### PR TITLE
chore: update outdated dependencies

### PR DESCRIPTION
**Pull request by SimenB**
- updates all dependencies to `latest`
  - most are just dropping old nodes
  - `lint-staged` warns on `git add` since it does it automatically, so I just removed that part
  - `eslint` has new recommended rules, fixed the `no-prototyupe-builtins` error
  - prettier wanted some new spacing
- added trailing commas all over
- updated ecmascript version in eslint in order to support ^

All are in individual commits to ease review.

### CODE REVIEW

**Comment by SimenB** [comment]
Conflict resolution _should_ be "accept my local diff, and do `yarn lint --fix` (or npm equivalent) but I can back out that change for now and reapply after we land some PRs

**Comment by sam-github** [comment]
Is it just me? eslint is telling me that it hates aggregatorsTest.js, which I have not changed:
```
/home/sam/s/prom_client_nodejs/test/aggregatorsTest.js
  10:13  error  Replace `⏎↹↹↹↹{·labels:·[],·value:·1·},⏎↹↹↹↹{·labels:·['label1'],·value:·2·}⏎↹↹↹` with `{·labels:·[],·value:·1·},·{·labels:·['label1'],·value:·2·}`  prettier/
prettier
  19:13  error  Replace `⏎↹↹↹↹{·labels:·[],·value:·3·},⏎↹↹↹↹{·labels:·['label1'],·value:·4·}⏎↹↹↹` with `{·labels:·[],·value:·3·},·{·labels:·['label1'],·value:·4·}`  prettier/
prettier
```

I'm not at all sure what that means.

**Comment by SimenB** [comment]
did you run `npm/yarn install`? That's the one change between `prettier@1.17.1` and `1.19.1`

**Comment by sam-github** [comment]
That was it. The eslint errors are pretty cryptic.

**Pull request merged**
