### PR TITLE
Allow setting Gauge values to NaN.

### PR DESCRIPTION
**Pull request by TimDumol**
This should fix https://github.com/siimon/prom-client/issues/168

### CODE REVIEW

**Comment by chriswessels** [comment]
Would be really grateful for a merge on this @siimon!

**Comment by SimenB** [comment]
@TimDumol mind updating the changelog as well?

**Comment by chriswessels** [comment]
Thank you @SimenB and @TimDumol :)

**Comment by siimon** [comment]
Sorry for taking too long, blaming the summer 😊

LGTM too

**Pull request merged**
