### PR TITLE
Print deprecation warnings on deprecated constructors

### PR DESCRIPTION
**Pull request by SimenB**
Since the next is a major anyways, might get this is.

### CODE REVIEW

**Comment by siimon** [comment]
I'm not sure we should do that already, want folks to have some more time to migrate since it will literally break all metrics. Should we add a deprecation warning in this release instead?

**Comment by SimenB** [comment]
Yeah, that makes sense

**Comment by SimenB** [comment]
@siimon Updated.

**Comment by SimenB** [comment]
One thing to note is that the java client support having 2 strings provided directly (name and help). It's only when you add labels, custom buckets/percentiles etc that it forces you to be explicit. Should we support the same thing?

If passed 2 arguments, check that they're both strings, and use as name and help. Otherwise print deprecation warning (if not an object).

**Comment by siimon** [comment]
I rather just have a configuration object to keep the api simple, what do you think?

**Pull request merged**
