### PR TITLE
Fix push gateway attempting to write promise instead of awaiting

### PR DESCRIPTION
**Pull request by adorin**
Added tests for push gateway awaiting on registry.metrics() #390 

Includes the fix proposed in https://github.com/siimon/prom-client/pull/392/files#r487438436

### CODE REVIEW

**Comment by adorin** [comment]
@zbjornson I took the liberty to commit your proposed fix and add tests, hoping this would expedite the process.

**Review by zbjornson — APPROVED** [review]
Yay, thanks so much!

Will give the other maintainers a chance to review, but for the sake of time will merge tomorrow if there are no other comments.

**Comment by zbjornson** [comment]
Thanks again!

**Comment by SleepWalker** [comment]
Hello, when this will be released?

**Pull request merged**
