### PR TITLE
Allow registering default metrics to other registries

### PR DESCRIPTION
**Pull request by SimenB**
Maybe take an object to `collectDefaultMetrics`? I'm going to tackle custom labels for the default metrics now, yet another option and it gets quite hairy

### CODE REVIEW

**Comment by siimon** [comment]
To get consistent, maybe there should only be one argument with a configuration object?

**Comment by siimon** [comment]
But maybe support both versions in this release and add a deprecation warning?

**Comment by siimon** [comment]
Sigh, just read the comment you wrote about configuration object so nvm about my first comment..

**Comment by SimenB** [comment]
I'll change it to an object and support both variants 🙂

**Comment by SimenB** [comment]
Updated 🙂

**Comment by SimenB** [comment]
@siimon I rebased this, and the comments were lost... If you comment on the PR instead of the commit, it should be ok.

Only missing this, and I'll cut a v10.

**Comment by SimenB** [comment]
Git reflog to the rescue: https://github.com/siimon/prom-client/commit/5f7a633649721d24984c6c74f2facf2af94fbe7f

**Comment by SimenB** [comment]
@siimon anything else before release? Or should I go ahead with 10?

**Comment by siimon** [comment]
Nope, not that I know of!

**Comment by SimenB** [comment]
Awesome.

https://github.com/siimon/prom-client/releases/tag/v10.0.0

**Comment by siimon** [comment]
Great work!

**Pull request merged**
