### PR TITLE
Remove timestamp from static metrics.

### LINKED ISSUE #114: nodejs_version_info not working with timestamp
Since the timestamp for `nodejs_version_info` is stale it looks like prometheus stops scraping the metric after a short while, and therefor the data does not appear when querying for it.

screenshot 2017-06-16 15 34 27

### PR DESCRIPTION
**Pull request by sgulseth**
Fixes #114

### CODE REVIEW

**Comment by siimon** [comment]
👍

**Comment by SimenB** [comment]
@siimon could you do a release?

**Comment by siimon** [comment]
Won't be able to do that for about 2 weeks, on vacation without a computer. Are you able to manage for that long?

**Comment by SimenB** [comment]
You could give me publish access? :angel: I'm good, but that's because we haven't upgraded to 9 yet.

**Comment by siimon** [comment]
You got it 😀

**Comment by SimenB** [comment]
Woo, awesome! 😄

**Comment by SimenB** [comment]
Published 🙂

**Pull request merged**
