### PR TITLE
Add summary metric type

### PR DESCRIPTION
**Pull request by pnieuwenhuis**
I've added a summary metric type to report to Prometheus. Added a dependency to TDigest to calculate the percentiles. Also reports count and sum of each label.

Also includes tests for the summary metric type.

### CODE REVIEW

**Comment by siimon** [comment]
Awesome work! Thank you!

The implementation lgtm, there are some comments in summary.js pointing to histogram that needs to be changed.. Also could you document the utility functions in the readme aswell?

Thanks!

**Comment by pnieuwenhuis** [comment]
I've made some additions to the README and altered the comments in `summary.js`.

**Comment by siimon** [comment]
Perfect! Thanks!

**Comment by ceecko** [comment]
Nice work. I was wondering if it's possible to define a duration for which an observation stays relevant for the summary and a number of buckets for rotation. Such as 15mins over 5 buckets.
See MaxAge and AgeBuckets setting in [Go client's SummaryOpts](https://godoc.org/github.com/prometheus/client_golang/prometheus#SummaryOpts)

**Pull request merged**
